# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:


# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/xxxx
- slug: twitter
  url: https://twitter.com/xxxx
- slug: rss
  url: /atom.xml

#  Add Google analytics tracking ID here
# google_analytics: 

# Banner
banner:
  # Show image in banner
  image: true
  # Show Hitokoto in home page banner, if false will display subtitle or title
  hitokoto: true
  # Banner image use imagelist or lovewallpaper
  customimage: false
  # Banner image list
  imagelist:
  - http://i.imgur.com/xxx1.jpg
  - http://i.imgur.com/xxx2.jpg
  - /images/banner/xxx3.png
  - /images/banner/xxx4.png